<a href="https://colab.research.google.com/github/J0SAL/Learning-DL/blob/main/codebasics/9.%20word_embeddings/1.%20keras%20embedding%20layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Word embedding using keras embedding layer
- supervised

In [15]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement'] #X

sentiment = np.array([1,1,1,1,1,0,0,0,0,0]) #y

In [16]:
one_hot("amazing restaurant",30)

[7, 20]

In [17]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[18, 6], [7, 20], [17, 18], [6, 9, 3], [24, 14, 29], [29, 6], [8, 14, 17], [5, 5], [5, 20], [21, 28]]


In [18]:
# adding padding to make all sentence length equal
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[18  6  0  0]
 [ 7 20  0  0]
 [17 18  0  0]
 [ 6  9  3  0]
 [24 14 29  0]
 [29  6  0  0]
 [ 8 14 17  0]
 [ 5  5  0  0]
 [ 5 20  0  0]
 [21 28  0  0]]


In [19]:
embeded_vector_size = 5 #5 features for a single word

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [20]:
# renaming for simplicity
X = padded_reviews
y = sentiment

In [21]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

# max sentence lenght - 4
# max feature size - 5
# combining 4x5 - 20


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten_1 (Flatten)         (None, 20)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [22]:
# train
model.fit(X, y, epochs=50, verbose=0)

In [23]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 140ms/step - loss: 0.6629 - accuracy: 1.0000


1.0

In [24]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [25]:
weights
# here are all the weights/features for all the words

array([[-9.78680551e-02, -8.24200287e-02,  5.45406081e-02,
         8.81870762e-02,  1.58364419e-02],
       [ 9.02637839e-05,  3.58499996e-02, -2.80221459e-02,
        -1.25683658e-02,  4.73877080e-02],
       [-2.93541700e-04, -4.55520153e-02, -4.89594452e-02,
         3.30250748e-02, -4.35574912e-02],
       [ 9.24173370e-02,  1.02190129e-01, -9.61081684e-02,
        -3.13843936e-02, -2.81272829e-02],
       [ 1.44953020e-02, -4.17479500e-02, -1.27492771e-02,
         4.06990089e-02,  3.80802043e-02],
       [-4.10913723e-03,  3.60431746e-02,  5.62870428e-02,
         9.93414894e-02, -6.74327910e-02],
       [ 2.94070039e-02, -8.23434629e-03, -1.87690854e-02,
        -6.85282424e-02, -2.40038000e-02],
       [ 1.89434886e-02, -2.99409479e-02, -5.80079388e-03,
        -2.33867187e-02, -6.95640454e-03],
       [-9.68142971e-02,  3.01088430e-02,  6.35158569e-02,
         4.41660583e-02,  7.92849064e-02],
       [ 4.52709384e-02, -7.97579736e-02,  4.26264517e-02,
        -2.06861552e-02

In [26]:
weights[4]

array([ 0.0144953 , -0.04174795, -0.01274928,  0.04069901,  0.0380802 ],
      dtype=float32)

Node: Embeddings can be saved and used later 